# Homework 1 Part 2: SQL

To start with, if you felt the class was unclear, check out the following tutorial: https://mode.com/sql-tutorial/introduction-to-sql/

Now! We'll be using sqlite to access a database. Start by downloading the sql lite file and putting it in the same directory as this notebook: https://www.kaggle.com/datasets/kaggle/sf-salaries (hit the 'download' button in the upper right). Check out the description of the data so you know the table / column names.

The following code will use sqlite to create a database connection.

In [62]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database.sqlite")
crsr = conn.cursor()

Before we proceed, please note that every task **must be completed using a single SQL query**, unless mentioned otherwise or given as prompt.     
(e.g. using print statements are fine, but you should not be using pandas library to work with the dataset.) The query should be stored in the query variable, like so:

query = 'your query here'

# Exploration

Problem 1:

Try to create a query that gives you a data frame of the EmployeeName, JobTitle, and BasePay from the salaries table. Use `df1` as the pandas DataFrame variable to store your query result

In [63]:
query = 'SELECT EmployeeName, JobTitle, BasePay FROM salaries'
df1 = pd.read_sql(query, conn)
df1.head()

,EmployeeName,JobTitle,BasePay
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6

Problem 2.

Modify your query from Problem 1 to limit it to the year 2012. Use `df2` as the pandas DataFrame variable to store your query result. Remember to include column `Year` in the final results.

In [64]:
query = 'SELECT EmployeeName, JobTitle, BasePay, Year FROM salaries WHERE Year = 2012'
df2 = pd.read_sql(query, conn)
df2.head()

         EmployeeName                      JobTitle    BasePay  Year
0      Gary Altenberg  Lieutenant, Fire Suppression  128808.87  2012
1        Gregory Suhr               Chief of Police  302578.00  2012
2          Khoa Trinh   Electronic Maintenance Tech  111921.00  2012
3  Joanne Hayes-White        Chief, Fire Department  296943.01  2012
4   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19  2012

Problem 3:

Further limit the table to the year 2012, employees making under 150,000, and sort in descending order by salary. Use `df3` as the pandas DataFrame variable to store your query result. Again, include column `Year` in the final results.

In [65]:
query = 'SELECT EmployeeName, JobTitle, BasePay, Year FROM salaries WHERE Year = 2012 AND BasePay < 150000 ORDER BY BasePay DESC'
df3 = pd.read_sql(query, conn)
df3.head()

           EmployeeName                     JobTitle    BasePay  Year
0      Julie Kirschbaum            Project Manager 3  149881.06  2012
1          Eric Jamison  Senior Physician Specialist  149746.72  2012
2  Daisy Mae Quitoriano                Nurse Manager  149657.87  2012
3        Ruth Armstrong           Nurse Practitioner  149169.48  2012
4     Stuart Washington  Senior Physician Specialist  148811.73  2012

# Aggregation

Problem 4:

Get the average base pay from the table. Use `AverageBasePay` as the column name for the average base pay in your query result and Use `df4` as the pandas DataFrame variable to store your query result

In [66]:
query = 'SELECT AVG(BasePay) as AverageBasePay FROM salaries'
df4 = pd.read_sql(query, conn)
df4.head()

   AverageBasePay
0    66053.729288

Problem 5:

Produce and print the head of a dataframe that shows the average pay for each year (only use a single, simple query). Your result should have a column `Year` for the year and a column `AverageBasePay` for the average base pay. Use `df5` as the pandas DataFrame variable to store your query result

In [67]:
query = 'SELECT Year, AVG(BasePay) as AverageBasePay  FROM salaries GROUP BY Year'
df5 = pd.read_sql(query, conn)
print(df5)

   Year  AverageBasePay
0  2011    63595.956517
1  2012    65436.406857
2  2013    68509.832156
3  2014    66557.437750

Problem 6:

Create a dataframe with averages of base pay, benefits, and overtime for each job title, as well as a column with the average of these three values. Use `JobTitle`, `AvgBasePay`, `AvgBenefits`, `AvgOvertimePay`, `AvgTotal` as the column name respectively. Use `df6` as the pandas DataFrame variable to store your query result

In [68]:
query = 'SELECT JobTitle, AVG(BasePay) AS AvgBasePay, AVG(Benefits) AS AvgBenefits, AVG(OvertimePay) AS AvgOvertimePay, (AVG(BasePay) + AVG(Benefits) + AVG(OvertimePay))/3 AS AvgTotal FROM salaries GROUP BY JobTitle'
df6 = pd.read_sql(query, conn)
df6.head()

,JobTitle,AvgBasePay,AvgBenefits,AvgOvertimePay,AvgTotal
0,ACCOUNT CLERK,43300.806506,0.00,373.200843,14558.002450
1,ACCOUNTANT,46643.172000,0.00,0.000000,15547.724000
2,ACCOUNTANT INTERN,28732.663958,0.00,24.430625,9585.698194
3,"ACPO,JuvP, Juv Prob (SFERS)",62290.780000,17975.59,0.000000,26755.456667
4,ACUPUNCTURIST,66374.400000,0.00,0.000000,22124.800000

# Table Creation

Problem 7:

Now we'll create our own table in our database. Separate the Salaries table by Year, and add it back to the database. (You may use basic python to complete the task, however, should still use SQL to query the data.)

Use `Y` + `Year` as the table name (i.e. `Y2011`).

Use `df7_list` as a list variable of dataframe to save the data. For example, `df7_list[0]` will represent Year 2011's data.

In [69]:
df7_list = []
for y in ['2011','2012','2013','2014']:
    query = f"SELECT * FROM salaries WHERE Year = '{y}'"
    df7 = pd.read_sql(query, conn)
    df7.to_sql(name='Y'+y, con=conn, if_exists='replace')
    df7_list.append(df7)

df7_list[0].head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,,326373.19,326373.19,2011,,San Francisco,

# Table Joining

Problem 8:

We'll move on to a new dataset for the next steps.
Download the dataset from here (https://www.kaggle.com/datasets/luizpaulodeoliveira/imdb-project-sql) and load the sqlite file same as before. Start by just selecting everything in the "movies" table to see what it looks like. Use `df8` as the pandas DataFrame variable to store your query result

In [70]:
conn = sqlite3.connect("movies.sqlite")
query = 'SELECT * FROM movies'
df8 = pd.read_sql(query, conn)
df8.head()

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43599,Spectre,245000000,107,2015-10-26,880674609,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,206647,4764
3,43600,The Dark Knight Rises,250000000,112,2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...,The Legend Ends,49026,4765
4,43601,John Carter,260000000,43,2012-03-07,284139100,John Carter,6.1,2124,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",49529,4766

Problem 9:

Create a dataframe that includes the entire contents of "movies" table as well as the director's name. Use `director_name` as the column name of the directore's name. Use `df9` as the pandas DataFrame variable to store your query result

In [71]:
# check the schema of the directors table
query = "PRAGMA table_info(directors)"
df = pd.read_sql(query, conn)
print(df.head())

query = 'SELECT movies.*, directors.name AS director_name FROM movies, directors LIMIT 4000;'
df9 = pd.read_sql(query, conn)
df9.head()

   cid        name     type  notnull dflt_value  pk
0    0        name     TEXT        0       None   0
1    1          id  INTEGER        0       None   1
2    2      gender  INTEGER        0       None   0
3    3         uid  INTEGER        0       None   0
4    4  department     TEXT        0       None   0

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id,director_name
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762,James Cameron
1,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762,Gore Verbinski
2,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762,Sam Mendes
3,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762,Christopher Nolan
4,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762,Andrew Stanton

# Analysis

The next few problems will be more involved! You'll need to combine some concepts you've learned. For each cell, show your work.
\
Remember, the answers should be in **a single query**.

\
Problem 10:

What is the average budget used for the top 10 grossing movies? Your result should have a column `avg_budget` for the average budget used for the top 10 grossing movies. Use `df10` as the pandas DataFrame variable to store your query result

In [72]:
query = 'SELECT AVG(sub.budget) AS avg_budget FROM (SELECT budget, revenue FROM movies ORDER BY revenue DESC LIMIT 10) AS sub;'
df10 = pd.read_sql(query, conn)
df10.head()

    avg_budget
0  195100000.0

Problem 11:

Which directors have the highest overall voting average? - show the top 5 directors' name and their average rating. Your result should have a column `ave_rating` and a column `director_name`. Use `df11` as the pandas DataFrame variable to store your query result

In [78]:
query = 'SELECT AVG(movies.vote_average) AS avg_rating, directors.name AS director_name FROM movies INNER JOIN directors ON movies.director_id = directors.id GROUP BY directors.name ORDER BY AVG(movies.vote_average) DESC LIMIT 5; '
df11 = pd.read_sql(query, conn)
df11.head()

   avg_rating  director_name
0       10.00    Gary Sinyor
1        9.50   Rohit Jugraj
2        9.30     Lance Hool
3        8.50   Floyd Mutrux
4        8.45  Tim McCanlies

Problem 12:

What are the top five directors by how much their average budget is? Your result should have a column `ave_budget` and a column `director_name`. Use `df12` as the pandas DataFrame variable to store your query result

In [74]:
# Problem 12: Top 5 directors by average budget
query = 'SELECT directors.name AS director_name, AVG(movies.budget) AS avg_budget FROM movies INNER JOIN directors ON movies.director_id = directors.id GROUP BY directors.name ORDER BY AVG(movies.budget) DESC LIMIT 5;'
df12 = pd.read_sql(query, conn)
df12.head()

    director_name    avg_budget
0    Byron Howard  2.600000e+08
1     Lee Unkrich  2.000000e+08
2     Dan Scanlon  2.000000e+08
3     David Yates  1.933333e+08
4  Brenda Chapman  1.850000e+08